GET http://localhost:5000/authors

###
POST http://localhost:5000/authors
Content-Type: application/json

{
    "name": "Giacomo",
    "email": "sadsfdsf@adsad.it",
    "age": 45,
    "approved": true
}
###

DELETE http://localhost:5000/authors/66ad0188cefcf48d9c5401f6

###

PUT http://localhost:5000/authors/66acf7150e43998c09109b1a
Content-Type: application/json

{
    "name" : "Carlo"
}

###

GET http://localhost:5000/authors/66acfc3905cd283271ecfacd